// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ClientForm.DAL.Models;

[Table("Client")]
public partial class Client
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(50)]
    public string Description { get; set; }

    [StringLength(50)]
    public string Job { get; set; }

    [StringLength(50)]
    public string EnteredBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime EntryDate { get; set; }

    [StringLength(50)]
    public string LastModificationBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastModificationIn { get; set; }

    [StringLength(50)]
    public string SalesMan { get; set; }

    [StringLength(50)]
    public string ClientSource { get; set; }

    [StringLength(50)]
    public string ClientClass { get; set; }
}